language: python

virtualenv:
  system_site_packages: false

python:
  - "2.7"

env:
  - PACKAGES=false

install:
  - cd climas-ng
  - pip install setuptools --upgrade
  - python setup.py install

script:
  # actually run the tests
  - python setup.py test
